# Generated by Django 4.2.5 on 2023-10-11 12:57
from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("lnschema_core", "0001_initial"),
        ("lnschema_core", "0002_alter_user_name"),
        ("lnschema_core", "0003_alter_storage_region_alter_transform_short_name"),
        ("lnschema_core", "0004_rename_folder_tag_alter_project_folders"),
        ("lnschema_core", "0005_alter_run_inputs_delete_runinput"),
        ("lnschema_core", "0006_feature_dataset"),
        ("lnschema_core", "0007_feature_synonyms_featureset_field_and_more"),
        ("lnschema_core", "0008_file_hash_type_transform_parents"),
        ("lnschema_core", "0009_remove_featureset_files_feature_unit_and_more"),
        ("lnschema_core", "0010_dataset_categories_file_categories"),
        ("lnschema_core", "0011_label_remove_tag_created_by_remove_tag_parents_and_more"),
        ("lnschema_core", "0012_remove_label_ref_id_remove_label_ref_orm_and_more"),
        ("lnschema_core", "0013_remove_feature_labels_orm_and_more"),
        ("lnschema_core", "0014_rename_ref_field_featureset_registry"),
        ("lnschema_core", "0015_file_initial_version_file_version"),
        ("lnschema_core", "0016_dataset_input_of_dataset_run_dataset_transform_and_more"),
        ("lnschema_core", "0017_dataset_initial_version_dataset_version"),
        ("lnschema_core", "0018_rename_datasetlabel_datasetulabel_and_more"),
        ("lnschema_core", "0019_dataset_reference_dataset_reference_type_and_more"),
        ("lnschema_core", "0020_run_report_transform_latest_report_and_more"),
        ("lnschema_core", "0021_dataset_storage_alter_dataset_file"),
        ("lnschema_core", "0022_migrate_to_integer_pks"),
    ]

    dependencies = []  # type: ignore
