# Generated by Django 5.0.6 on 2024-05-16 09:35

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models

import lnschema_core.ids
import lnschema_core.models
import lnschema_core.types
import lnschema_core.users


class Migration(migrations.Migration):
    replaces = [
        ("lnschema_core", "0001_initial_squashed_0023"),
        ("lnschema_core", "0024_import_legacy_data"),
        ("lnschema_core", "0025_remove_user_email"),
        ("lnschema_core", "0026_dataset_visibility_file_visibility"),
        ("lnschema_core", "0027_file_key_is_virtual"),
        ("lnschema_core", "0028_alter_dataset_visibility_alter_file_visibility"),
        (
            "lnschema_core",
            "0029_remove_feature_modality_remove_featureset_modality_and_more",
        ),
        ("lnschema_core", "0030_alter_dataset_visibility_alter_file_visibility"),
        ("lnschema_core", "0031_rename_file_to_artifact"),
        ("lnschema_core", "0032_remove_dataset_storage"),
        (
            "lnschema_core",
            "0033_alter_artifact_unique_together_artifact_n_objects_and_more",
        ),
        ("lnschema_core", "0034_run_environment"),
        ("lnschema_core", "0035_remove_artifact_initial_version_and_more"),
        ("lnschema_core", "0036_storage_description"),
        ("lnschema_core", "0037_rename_dataset_to_collection"),
        (
            "lnschema_core",
            "0038_alter_collection_artifact_alter_collection_artifacts_and_more",
        ),
        (
            "lnschema_core",
            "0039_remove_collection_artifacts_collectionartifact_and_more",
        ),
        ("lnschema_core", "0040_alter_transform_type"),
        (
            "lnschema_core",
            "0041_remove_transform_short_name_transform_description_and_more",
        ),
        ("lnschema_core", "0042_rename_run_at_run_started_at_run_finished_at"),
        ("lnschema_core", "0043_run_json"),
        ("lnschema_core", "0044_run_replicated_outputs_transform_ulabels_and_more"),
        (
            "lnschema_core",
            "0045_rename_replicated_outputs_run_replicated_output_artifacts_and_more",
        ),
        ("lnschema_core", "0046_storage_instance_uid"),
        ("lnschema_core", "0047_featurevalue_artifactfeaturevalue_and_more"),
    ]
