# Generated by Django 4.2.1 on 2023-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0002_alter_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
