# Generated by Django 4.2.2 on 2023-07-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0012_remove_label_ref_id_remove_label_ref_orm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="labels_orm",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="labels_schema",
        ),
        migrations.AddField(
            model_name="feature",
            name="label_orms",
            field=models.CharField(db_index=True, default=None, max_length=128, null=True),
        ),
    ]
