# Generated by Django 4.2.2 on 2023-08-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0014_rename_ref_field_featureset_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="stem_id",
            field=models.CharField(db_index=True, default=None, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="version",
            field=models.CharField(db_index=True, default=None, max_length=10, null=True),
        ),
    ]
