# Generated by Django 4.2.2 on 2023-10-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0019_dataset_reference_dataset_reference_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="report",
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="report_of", to="lnschema_core.file"),
        ),
        migrations.AddField(
            model_name="transform",
            name="latest_report",
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="latest_report_of", to="lnschema_core.file"),
        ),
        migrations.AddField(
            model_name="transform",
            name="source_file",
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="source_of", to="lnschema_core.file"),
        ),
        migrations.AlterField(
            model_name="file",
            name="transform",
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="output_files", to="lnschema_core.transform"),
        ),
        migrations.AddField(
            model_name="run",
            name="is_consecutive",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
