# Generated by Django 4.2.5 on 2023-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0026_dataset_visibility_file_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="key_is_virtual",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
