# Generated by Django 4.2.5 on 2023-12-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0033_alter_artifact_unique_together_artifact_n_objects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="environment",
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="environment_of", to="lnschema_core.artifact"),
        ),
    ]
