# Generated by Django 5.1 on 2024-01-07 19:00

import django.db.models.deletion
from django.db import migrations, models

import lnschema_core.models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0038_alter_collection_artifact_alter_collection_artifacts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionArtifact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("artifact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lnschema_core.artifact")),
                ("collection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lnschema_core.collection")),
            ],
            options={
                "unique_together": {("collection", "artifact")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AlterField(
            model_name="collection",
            name="artifacts",
            field=models.ManyToManyField(related_name="collections", through="lnschema_core.CollectionArtifact", to="lnschema_core.artifact"),
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="artifacts",
            new_name="unordered_artifacts",
        ),
    ]
