# Generated by Django 5.1 on 2024-03-09 05:20

from django.db import migrations, models

import lnschema_core.types


class Migration(migrations.Migration):
    dependencies = [
        (
            "lnschema_core",
            "0039_remove_collection_artifacts_collectionartifact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transform",
            name="type",
            field=models.CharField(
                choices=[
                    ("pipeline", "pipeline"),
                    ("notebook", "notebook"),
                    ("upload", "upload"),
                    ("script", "script"),
                ],
                db_index=True,
                default=lnschema_core.types.TransformType["pipeline"],
                max_length=20,
            ),
        ),
    ]
