# Generated by Django 5.1 on 2024-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0040_alter_transform_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transform",
            name="short_name",
        ),
        migrations.AddField(
            model_name="transform",
            name="description",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transform",
            name="key",
            field=models.CharField(db_index=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="collection",
            name="reference_type",
            field=models.CharField(db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="feature",
            name="registries",
            field=models.CharField(db_index=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="featureset",
            name="name",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="featureset",
            name="registry",
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="run",
            name="reference_type",
            field=models.CharField(db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="transform",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transform",
            name="reference_type",
            field=models.CharField(db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ulabel",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="ulabel",
            name="reference_type",
            field=models.CharField(db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
    ]
