# Generated by Django 5.1 on 2024-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lnschema_core",
            "0041_remove_transform_short_name_transform_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="run_at",
            new_name="started_at",
        ),
        migrations.AddField(
            model_name="run",
            name="finished_at",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
