# Generated by Django 5.1 on 2024-03-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0042_rename_run_at_run_started_at_run_finished_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="json",
            field=models.JSONField(default=None, null=True),
        ),
    ]
