# Generated by Django 5.1 on 2024-04-16 18:35

from django.db import migrations, models

import lnschema_core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0043_run_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="replicated_outputs",
            field=models.ManyToManyField(
                related_name="replicating_runs", to="lnschema_core.artifact"
            ),
        ),
        migrations.AddField(
            model_name="transform",
            name="ulabels",
            field=models.ManyToManyField(
                related_name="transforms", to="lnschema_core.ulabel"
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="uid",
            field=models.CharField(
                db_index=True,
                default=lnschema_core.ids.base62_12,
                max_length=12,
                unique=True,
            ),
        ),
    ]
