# Generated by Django 5.1 on 2024-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0043_run_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="replicated_outputs",
            field=models.ManyToManyField(
                related_name="replicating_runs", to="lnschema_core.artifact"
            ),
        ),
    ]
