# Generated by Django 5.1 on 2024-04-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0044_run_replicated_outputs_transform_ulabels_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="replicated_outputs",
            new_name="replicated_output_artifacts",
        ),
        migrations.AddField(
            model_name="run",
            name="replicated_output_collections",
            field=models.ManyToManyField(
                related_name="replicating_runs", to="lnschema_core.collection"
            ),
        ),
    ]
