# Generated by Django 5.1 on 2024-04-27 15:09

from django.db import migrations, models

import lnschema_core.types


class Migration(migrations.Migration):
    dependencies = [
        (
            "lnschema_core",
            "0045_rename_replicated_outputs_run_replicated_output_artifacts_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="instance_uid",
            field=models.CharField(
                db_index=True, default=None, max_length=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="type",
            field=models.CharField(
                choices=[
                    ("pipeline", "pipeline"),
                    ("notebook", "notebook"),
                    ("upload", "upload"),
                    ("script", "script"),
                    ("function", "function"),
                ],
                db_index=True,
                default=lnschema_core.types.TransformType["pipeline"],
                max_length=20,
            ),
        ),
    ]
