# Generated by Django 5.0.6 on 2024-05-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0047_featurevalue_artifactfeaturevalue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactulabel",
            name="feature",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lnschema_core.feature",
            ),
        ),
        migrations.AlterField(
            model_name="collectionulabel",
            name="feature",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lnschema_core.feature",
            ),
        ),
    ]
