# Generated by Django 5.0.6 on 2024-05-17 20:40

import django.db.models.deletion
from django.db import migrations, models

import lnschema_core.ids
import lnschema_core.models
import lnschema_core.types
import lnschema_core.users


class Migration(migrations.Migration):
    replaces = [
        (
            "lnschema_core",
            "0037_rename_dataset_to_collection",
        ),
        (
            "lnschema_core",
            "0038_alter_collection_artifact_alter_collection_artifacts_and_more",
        ),
        (
            "lnschema_core",
            "0039_remove_collection_artifacts_collectionartifact_and_more",
        ),
        ("lnschema_core", "0040_alter_transform_type"),
        (
            "lnschema_core",
            "0041_remove_transform_short_name_transform_description_and_more",
        ),
        ("lnschema_core", "0042_rename_run_at_run_started_at_run_finished_at"),
        ("lnschema_core", "0043_run_json"),
        ("lnschema_core", "0044_run_replicated_outputs_transform_ulabels_and_more"),
        (
            "lnschema_core",
            "0045_rename_replicated_outputs_run_replicated_output_artifacts_and_more",
        ),
        ("lnschema_core", "0046_storage_instance_uid"),
        ("lnschema_core", "0047_featurevalue_artifactfeaturevalue_and_more"),
        ("lnschema_core", "0048_alter_artifactulabel_feature_and_more"),
        ("lnschema_core", "0049_rename_type_feature_dtype_and_more"),
    ]

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "version",
                    models.CharField(
                        db_index=True, default=None, max_length=10, null=True
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "suffix",
                    models.CharField(db_index=True, default=None, max_length=30),
                ),
                (
                    "accessor",
                    models.CharField(
                        db_index=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True, default=None, max_length=255, null=True
                    ),
                ),
                ("size", models.BigIntegerField(db_index=True, null=True)),
                (
                    "hash",
                    models.CharField(
                        db_index=True, default=None, max_length=86, null=True
                    ),
                ),
                (
                    "hash_type",
                    models.CharField(
                        db_index=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "n_objects",
                    models.BigIntegerField(db_index=True, default=None, null=True),
                ),
                (
                    "n_observations",
                    models.BigIntegerField(db_index=True, default=None, null=True),
                ),
                (
                    "visibility",
                    models.SmallIntegerField(
                        choices=[(1, "Default"), (0, "Hidden"), (-1, "Trash")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("key_is_virtual", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(lnschema_core.models.Data, models.Model),
        ),
        migrations.CreateModel(
            name="FeatureSet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True, default=None, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(default=None, max_length=150, null=True)),
                ("n", models.IntegerField()),
                ("dtype", models.CharField(default=None, max_length=64, null=True)),
                ("registry", models.CharField(db_index=True, max_length=120)),
                (
                    "hash",
                    models.CharField(
                        db_index=True, default=None, max_length=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Param",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=lnschema_core.ids.base62_12,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "root",
                    models.CharField(
                        db_index=True, default=None, max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True, default=None, max_length=255, null=True
                    ),
                ),
                ("type", models.CharField(db_index=True, max_length=30)),
                (
                    "region",
                    models.CharField(
                        db_index=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "instance_uid",
                    models.CharField(
                        db_index=True, default=None, max_length=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True, default=None, max_length=8, unique=True
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        db_index=True, default=None, max_length=30, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default=None, max_length=150, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, lnschema_core.models.CanValidate),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "version",
                    models.CharField(
                        db_index=True, default=None, max_length=10, null=True
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=lnschema_core.ids.base62_20,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, default=None, max_length=150)),
                ("description", models.TextField(default=None, null=True)),
                (
                    "hash",
                    models.CharField(
                        db_index=True, default=None, max_length=86, null=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        db_index=True, default=None, max_length=25, null=True
                    ),
                ),
                (
                    "visibility",
                    models.SmallIntegerField(
                        choices=[(1, "Default"), (0, "Hidden"), (-1, "Trash")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "artifact",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection",
                        to="lnschema_core.artifact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(lnschema_core.models.Data, models.Model),
        ),
        migrations.CreateModel(
            name="CollectionArtifact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.collection",
                    ),
                ),
            ],
            options={
                "unique_together": {("collection", "artifact")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AddField(
            model_name="collection",
            name="unordered_artifacts",
            field=models.ManyToManyField(
                related_name="collections",
                through="lnschema_core.CollectionArtifact",
                to="lnschema_core.artifact",
            ),
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=lnschema_core.ids.base62_12,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, default=None, max_length=150)),
                ("dtype", models.CharField(db_index=True, default=None, max_length=64)),
                (
                    "unit",
                    models.CharField(
                        db_index=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, default=None, null=True),
                ),
                ("synonyms", models.TextField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "feature_sets",
                    models.ManyToManyField(
                        related_name="features", to="lnschema_core.featureset"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=lnschema_core.users.current_user_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_features",
                        to="lnschema_core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, lnschema_core.models.CanValidate),
        ),
        migrations.CreateModel(
            name="CollectionFeatureSet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("slot", models.CharField(default=None, max_length=50, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.collection",
                    ),
                ),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.featureset",
                    ),
                ),
            ],
            options={
                "unique_together": {("collection", "feature_set")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AddField(
            model_name="collection",
            name="feature_sets",
            field=models.ManyToManyField(
                related_name="collections",
                through="lnschema_core.CollectionFeatureSet",
                to="lnschema_core.featureset",
            ),
        ),
        migrations.CreateModel(
            name="ArtifactFeatureSet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("slot", models.CharField(default=None, max_length=40, null=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.featureset",
                    ),
                ),
            ],
            options={
                "unique_together": {("artifact", "feature_set")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AddField(
            model_name="artifact",
            name="feature_sets",
            field=models.ManyToManyField(
                related_name="artifacts",
                through="lnschema_core.ArtifactFeatureSet",
                to="lnschema_core.featureset",
            ),
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "feature",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.feature",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=lnschema_core.users.current_user_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_feature_sets",
                        to="lnschema_core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArtifactFeatureValue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "feature_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.featurevalue",
                    ),
                ),
            ],
            options={
                "unique_together": {("artifact", "feature_value")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AddField(
            model_name="artifact",
            name="feature_values",
            field=models.ManyToManyField(
                through="lnschema_core.ArtifactFeatureValue",
                to="lnschema_core.featurevalue",
            ),
        ),
        migrations.CreateModel(
            name="ParamValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.param",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lnschema_core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=lnschema_core.ids.base62_20,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "finished_at",
                    models.DateTimeField(db_index=True, default=None, null=True),
                ),
                ("json", models.JSONField(default=None, null=True)),
                ("is_consecutive", models.BooleanField(default=None, null=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        db_index=True, default=None, max_length=25, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "environment",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="environment_of",
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "replicated_output_artifacts",
                    models.ManyToManyField(
                        related_name="replicating_runs", to="lnschema_core.artifact"
                    ),
                ),
                (
                    "replicated_output_collections",
                    models.ManyToManyField(
                        related_name="replicating_runs", to="lnschema_core.collection"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_of",
                        to="lnschema_core.artifact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="input_of",
            field=models.ManyToManyField(
                related_name="input_collections", to="lnschema_core.run"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="run",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="output_collections",
                to="lnschema_core.run",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="input_of",
            field=models.ManyToManyField(
                related_name="input_artifacts", to="lnschema_core.run"
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="run",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="output_artifacts",
                to="lnschema_core.run",
            ),
        ),
        migrations.CreateModel(
            name="RunParamValue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "param_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.paramvalue",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.run",
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "param_value")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AddField(
            model_name="run",
            name="param_values",
            field=models.ManyToManyField(
                related_name="runs",
                through="lnschema_core.RunParamValue",
                to="lnschema_core.paramvalue",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="storage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="lnschema_core.storage",
            ),
        ),
        migrations.CreateModel(
            name="Transform",
            fields=[
                (
                    "version",
                    models.CharField(
                        db_index=True, default=None, max_length=10, null=True
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True, default=None, max_length=16, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pipeline", "pipeline"),
                            ("notebook", "notebook"),
                            ("upload", "upload"),
                            ("script", "script"),
                            ("function", "function"),
                        ],
                        db_index=True,
                        default=lnschema_core.types.TransformType["pipeline"],
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        db_index=True, default=None, max_length=25, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "latest_report",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="latest_report_of",
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        related_name="children", to="lnschema_core.transform"
                    ),
                ),
                (
                    "source_code",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_code_of",
                        to="lnschema_core.artifact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(lnschema_core.models.HasParents, models.Model),
        ),
        migrations.AddField(
            model_name="run",
            name="transform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="lnschema_core.transform",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="transform",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="output_collections",
                to="lnschema_core.transform",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="transform",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="output_artifacts",
                to="lnschema_core.transform",
            ),
        ),
        migrations.CreateModel(
            name="ULabel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=lnschema_core.ids.base62_8,
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default=None, max_length=150, unique=True
                    ),
                ),
                ("description", models.TextField(default=None, null=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        db_index=True, default=None, max_length=25, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "parents",
                    models.ManyToManyField(
                        related_name="children", to="lnschema_core.ulabel"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=lnschema_core.users.current_user_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_ulabels",
                        to="lnschema_core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                lnschema_core.models.HasParents,
                lnschema_core.models.CanValidate,
            ),
        ),
        migrations.AddField(
            model_name="transform",
            name="ulabels",
            field=models.ManyToManyField(
                related_name="transforms", to="lnschema_core.ulabel"
            ),
        ),
        migrations.CreateModel(
            name="CollectionULabel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.collection",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lnschema_core.feature",
                    ),
                ),
                (
                    "ulabel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.ulabel",
                    ),
                ),
            ],
            options={
                "unique_together": {("collection", "ulabel")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AddField(
            model_name="collection",
            name="ulabels",
            field=models.ManyToManyField(
                related_name="collections",
                through="lnschema_core.CollectionULabel",
                to="lnschema_core.ulabel",
            ),
        ),
        migrations.CreateModel(
            name="ArtifactULabel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lnschema_core.feature",
                    ),
                ),
                (
                    "ulabel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lnschema_core.ulabel",
                    ),
                ),
            ],
            options={
                "unique_together": {("artifact", "ulabel")},
            },
            bases=(models.Model, lnschema_core.models.LinkORM),
        ),
        migrations.AddField(
            model_name="artifact",
            name="ulabels",
            field=models.ManyToManyField(
                related_name="artifacts",
                through="lnschema_core.ArtifactULabel",
                to="lnschema_core.ulabel",
            ),
        ),
        migrations.AddField(
            model_name="transform",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_transforms",
                to="lnschema_core.user",
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_storages",
                to="lnschema_core.user",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_runs",
                to="lnschema_core.user",
            ),
        ),
        migrations.AddField(
            model_name="param",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="lnschema_core.user"
            ),
        ),
        migrations.AddField(
            model_name="featureset",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_feature_sets",
                to="lnschema_core.user",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_collections",
                to="lnschema_core.user",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_artifacts",
                to="lnschema_core.user",
            ),
        ),
    ]
