# Generated by Django 5.2 on 2024-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0062_artifact_is_latest_collection_is_latest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="transform",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
