# Generated by Django 5.2 on 2024-11-15 15:48

import django.db.models.deletion
from django.db import migrations, models

import lnschema_core.fields
import lnschema_core.ids
import lnschema_core.models
import lnschema_core.users


class Migration(migrations.Migration):
    replaces = [
        ("lnschema_core", "0052_squashed"),
        (
            "lnschema_core",
            "0053_alter_featureset_hash_alter_paramvalue_created_by_and_more",
        ),
        ("lnschema_core", "0054_alter_feature_previous_runs_and_more"),
        ("lnschema_core", "0055_artifact_type_artifactparamvalue_and_more"),
        (
            "lnschema_core",
            "0056_rename_ulabel_ref_is_name_artifactulabel_label_ref_is_name_and_more",
        ),
        ("lnschema_core", "0057_link_models_latest_report_and_others"),
        ("lnschema_core", "0058_artifact__actions_collection__actions"),
        (
            "lnschema_core",
            "0059_alter_artifact__accessor_alter_artifact__hash_type_and_more",
        ),
        ("lnschema_core", "0060_alter_artifact__actions"),
        (
            "lnschema_core",
            "0061_alter_collection_meta_artifact_alter_run_environment_and_more",
        ),
        ("lnschema_core", "0062_add_is_latest_field"),
        ("lnschema_core", "0063_populate_latest_field"),
        (
            "lnschema_core",
            "0064_alter_artifact_version_alter_collection_version_and_more",
        ),
        ("lnschema_core", "0065_remove_collection_feature_sets_and_more"),
        ("lnschema_core", "0066_alter_artifact__feature_values_and_more"),
        ("lnschema_core", "0067_alter_featurevalue_unique_together_and_more"),
        ("lnschema_core", "0068_alter_artifactulabel_unique_together_and_more"),
        (
            "lnschema_core",
            "0069_alter_artifact__accessor_alter_artifact__hash_type_and_more",
        ),
    ]

    dependencies = []  # type: ignore
